version: '3'
services:
  orfanbase-api:
    container_name: orfanbase-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - DB_SERVER=orfanbase-db
      - POSTGRES_DB=orfanbase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=orfanbase
    depends_on:
      - orfanbase-db
    links:
      - orfanbase-db
    networks:
      - orfanid
  orfanbase-db:
    container_name: orfanbase-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=orfanbase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=orfanbase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - orfanid
volumes:
  db-data:
networks:
  orfanid:
    driver: "bridge"
