spring.application.name: ORFanbaseDB
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/orfanbase
    username: postgres
    password: root